#pragma kernel March

#include "Includes/MarchingCubesLookupTables.compute"
#include "Includes/HelperCompute.compute"

RWStructuredBuffer<float>    _Weights;
RWStructuredBuffer<Triangle> _Triangles;

float _IsoLevel;

struct Triangle{
	float3 a,b,c;
}

[numthreads(numThreads,numThreads,numThreads)]
void March (uint3 id : SV_DispatchThreadID)
{
	if(id.x >= _ChunkSize - 1 || id.y >= _ChunkSize - 1 || id.z >= _ChunkSize - 1)
	{
		return;
	}
	


}
